# Generated by Django 5.1.15 on 2026-09-10 12:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle / Bike'), ('SCOOTER', 'Scooter'), ('EV_BIKE', 'Electric Scooter / EV'), ('BICYCLE', 'Bicycle')], default='MOTORCYCLE', max_length=20)),
                ('vehicle_number', models.CharField(help_text='e.g. TS 09 EA 1234', max_length=30)),
                ('driving_license_number', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Online / Offline toggle for dispatching')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Partner Profile',
                'verbose_name_plural': 'Delivery Partner Profiles',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted by Partner'), ('PICKED_UP', 'Picked Up from Kitchen'), ('DELIVERED', 'Delivered to Customer'), ('REJECTED', 'Rejected / Reassigned')], default='ASSIGNED', max_length=20)),
                ('delivery_otp', models.CharField(blank=True, help_text='4 or 6-digit OTP code to confirm delivery handoff', max_length=6)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliverypartnerprofile')),
            ],
            options={
                'verbose_name': 'Delivery Assignment',
                'verbose_name_plural': 'Delivery Assignments',
            },
        ),
    ]
