# Generated by Django 5.1.15 on 2026-09-10 12:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nutrient – The Super Food', help_text='Official Restaurant Name', max_length=150)),
                ('tagline', models.CharField(default='Eat Clean. Stay Strong. Live Better.', help_text='Primary brand tagline', max_length=255)),
                ('secondary_tagline', models.CharField(blank=True, default='Clean Food, Real Ingredients, Real Results', max_length=255)),
                ('description', models.TextField(default='Nutrient – The Super Food is dedicated to nourishing your body with high-protein bowls, fresh gourmet salads, nutritious warm soups, and cold-pressed drinks. 100% clean, zero artificial preservatives, crafted fresh in Hyderabad.')),
                ('address_line', models.CharField(default='Madhapur / HITEC City', max_length=255)),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('pincode', models.CharField(default='500081', max_length=10)),
                ('phone', models.CharField(default='+91 7993476624', max_length=20)),
                ('whatsapp_number', models.CharField(default='+91 7993476624', max_length=20)),
                ('email', models.EmailField(default='contact@nutrientfood.in', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('is_accepting_orders', models.BooleanField(default=True, help_text='Master switch: Toggle OFF during kitchen overload or maintenance.')),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Max delivery radius from Hyderabad kitchen in KM', max_digits=5)),
                ('avg_preparation_time_mins', models.PositiveIntegerField(default=25, help_text='Average kitchen preparation time in minutes')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('199.00'), help_text='Minimum order total before checkout is allowed', max_digits=8)),
                ('default_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Standard delivery fee (₹)', max_digits=6)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Orders above this amount get free delivery', max_digits=8)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='GST percentage applied to food subtotal (e.g. 5.00%)', max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('17.448294'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('78.374184'), max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Profile',
                'verbose_name_plural': 'Restaurant Profile',
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField(default='09:00:00')),
                ('closing_time', models.TimeField(default='23:00:00')),
                ('is_closed', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='restaurant.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['day_of_week'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
    ]
