# Generated by Django 5.1.15 on 2026-09-11 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('WELCOME_CATALOG', 'Customer Welcome & Menu Catalog'), ('ORDER_STATUS', 'Order Status Update'), ('PROMOTIONAL', 'Promotional Broadcast')], default='WELCOME_CATALOG', max_length=30, unique=True)),
                ('title', models.CharField(default='Customer Welcome & Menu Highlights', max_length=150)),
                ('body_text', models.TextField(default="🥗 *Welcome to Nutrient – The Super Food, {customer_name}!* 🌿\nEat Clean. Stay Strong. Live Better.\n\nThank you for joining us! We prepare fresh, 100% clean, high-protein meals in Hyderabad with zero preservatives.\n\n🍲 *TODAY'S SPECIAL SUPER FOOD MENU (30% OFF)*:\n{menu_items}\n\n📅 *WEEKLY & MONTHLY SUBSCRIPTIONS*:\n{subscription_plans}\n\n🛵 *Order Now with Free Delivery within 3km*:\n{order_link}\n\n💬 Kitchen Hotline & WhatsApp: {kitchen_phone}")),
                ('is_active', models.BooleanField(default=True, help_text='Master switch: Automatically send this message when a new customer registers.')),
                ('include_live_menu', models.BooleanField(default=True)),
                ('include_subscriptions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent / Dispatched'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SENT', max_length=15)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_payload', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
