# Generated by Django 5.1.15 on 2026-09-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_whatsapptemplate_whatsappmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='message_type',
            field=models.CharField(db_index=True, default='WELCOME', max_length=30),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled daily dispatch time e.g. 07:30, 12:00, 16:30, 19:30', null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Registered Customers'), ('SUBSCRIBERS', 'Active Subscribers Only'), ('NON_SUBSCRIBERS', 'Non-Subscribers (Regular Diners) Only'), ('VEG', 'Vegetarian Preference'), ('NON_VEG', 'Non-Vegetarian / High Protein')], default='ALL', help_text='Filter recipient segment based on customer profile', max_length=25),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Master switch: Automatically send this message when triggered.'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='template_type',
            field=models.CharField(choices=[('WELCOME_CATALOG', 'Customer Welcome & Menu Catalog'), ('MEAL_BREAKFAST', 'Daily Breakfast Alert'), ('MEAL_LUNCH', 'Daily Lunch Alert'), ('MEAL_SNACK', 'Daily Evening Snack Alert'), ('MEAL_DINNER', 'Daily Dinner Alert'), ('ORDER_STATUS', 'Order Status Update'), ('PROMOTIONAL', 'Promotional Broadcast')], default='WELCOME_CATALOG', max_length=30, unique=True),
        ),
    ]
