# Generated by Django 5.1.15 on 2026-09-10 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('bowl_type', models.CharField(choices=[('VEG_PROTEIN', 'Veg Protein Bowl'), ('NON_VEG_PROTEIN', 'Non-Veg Protein Bowl'), ('VEG_MEAL', 'Vegetable Meal Bowl'), ('NON_VEG_MEAL', 'Non-Veg Meal Bowl')], db_index=True, max_length=20)),
                ('duration', models.CharField(choices=[('WEEKLY', 'Weekly (7 Bowls)'), ('MONTHLY', 'Monthly (30 Bowls)')], db_index=True, max_length=15)),
                ('total_bowls', models.PositiveIntegerField(default=7, help_text='Total bowls included in cycle')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original MRP without discount in ₹', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Discounted Subscriber Price in ₹ (70% of MRP)', max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(help_text='Plan summary and inclusions')),
                ('perks', models.JSONField(blank=True, default=list, help_text='List of plan highlights e.g. Free 3km delivery, Dressing & Drink included')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'bowl_type', 'duration'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('delivery_time_slot', models.CharField(choices=[('LUNCH', 'Lunch (12:30 PM – 01:30 PM)'), ('DINNER', 'Dinner (07:30 PM – 08:30 PM)')], default='LUNCH', max_length=15)),
                ('bowls_total', models.PositiveIntegerField(default=7)),
                ('bowls_delivered', models.PositiveIntegerField(default=0)),
                ('default_customization', models.JSONField(blank=True, default=dict, help_text='Default protein, base, veggies, dressing & drink preferences')),
                ('special_instructions', models.TextField(blank=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='PAID', max_length=20)),
                ('payment_method', models.CharField(default='ONLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_deliveries', to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySubscriptionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(db_index=True)),
                ('time_slot', models.CharField(choices=[('LUNCH', 'Lunch (12:30 PM – 01:30 PM)'), ('DINNER', 'Dinner (07:30 PM – 08:30 PM)')], default='LUNCH', max_length=15)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PREPARING', 'Preparing in Kitchen'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('SKIPPED', 'Skipped / Paused')], db_index=True, default='SCHEDULED', max_length=20)),
                ('customization', models.JSONField(blank=True, default=dict, help_text='Day-specific custom ingredients selected by customer')),
                ('delivery_notes', models.CharField(blank=True, max_length=255)),
                ('delivery_otp', models.CharField(blank=True, max_length=4)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_deliveries', to='subscriptions.customersubscription')),
            ],
            options={
                'verbose_name': 'Daily Subscription Delivery',
                'verbose_name_plural': 'Daily Subscription Deliveries',
                'ordering': ['delivery_date', 'time_slot'],
                'unique_together': {('subscription', 'delivery_date')},
            },
        ),
    ]
