# Generated by Django 5.1.15 on 2026-09-10 12:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief category description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display in customer menu')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(help_text='Ingredients, preparation style and flavor profile')),
                ('food_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], db_index=True, default='VEG', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular Price in ₹', max_digits=8)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted sale price in ₹', max_digits=8, null=True)),
                ('calories', models.PositiveIntegerField(db_index=True, default=350, help_text='Energy in kcal')),
                ('protein_grams', models.DecimalField(db_index=True, decimal_places=1, default=Decimal('20.0'), help_text='Protein in grams (g)', max_digits=5)),
                ('carbs_grams', models.DecimalField(decimal_places=1, default=Decimal('35.0'), help_text='Carbohydrates in grams (g)', max_digits=5)),
                ('fats_grams', models.DecimalField(decimal_places=1, default=Decimal('10.0'), help_text='Healthy Fats in grams (g)', max_digits=5)),
                ('fiber_grams', models.DecimalField(decimal_places=1, default=Decimal('5.0'), help_text='Dietary Fiber in grams (g)', max_digits=5)),
                ('is_high_protein', models.BooleanField(db_index=True, default=False, help_text='Mark if item provides high protein (e.g. >= 25g)')),
                ('is_calorie_conscious', models.BooleanField(db_index=True, default=False, help_text='Mark if item is low-calorie / weight management friendly')),
                ('is_zero_preservative', models.BooleanField(default=True, help_text='100% clean ingredients, no artificial chemicals or preservatives')),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_keto_friendly', models.BooleanField(default=False)),
                ('is_chef_special', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Instant kitchen in-stock / out-of-stock toggle')),
                ('preparation_time_mins', models.PositiveIntegerField(default=20, help_text='Estimated cooking/assembly time in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='menu.category')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['-is_bestseller', 'name'],
            },
        ),
    ]
