# Generated by Django 5.1.15 on 2026-09-10 18:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Choose Your Protein, Choose Veggies, Choose Dressing', max_length=100)),
                ('min_choices', models.PositiveIntegerField(default=1, help_text='Minimum number of choices required')),
                ('max_choices', models.PositiveIntegerField(default=1, help_text='Maximum number of choices allowed')),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_groups', to='menu.fooditem')),
            ],
            options={
                'verbose_name': 'Customization Group',
                'verbose_name_plural': 'Customization Groups',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost in ₹, if any', max_digits=6)),
                ('calories_modifier', models.IntegerField(default=0, help_text='Calories +/-')),
                ('protein_modifier', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Protein +/- in grams', max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.customizationgroup')),
            ],
            options={
                'verbose_name': 'Customization Option',
                'verbose_name_plural': 'Customization Options',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
