# Generated by Django 5.1.15 on 2026-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_customizationgroup_customizationoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='auto_timing_enabled',
            field=models.BooleanField(default=True, help_text='Automatically manage stock availability based on current meal timing'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, help_text="Active meal slots: ['BREAKFAST', 'LUNCH', 'SNACK', 'DINNER'] or ['ALL_DAY']"),
        ),
    ]
